import generalFormModel from "./generalFormModel";
const {
  formField: {

    general_name,
    general_lastname,
    general_age,
    general_place_birth,
    general_civil_status,
    general_profession,
    general_direction,
    general_time_reside,
    general_emergency_name,
    general_emergency_kinship,
    general_previous_direction,
    general_phone,
    general_emergency_phone,
    general_dpi,
    general_nit,
    general_email,

    family_dad_name,
    family_dad_age,
    family_dad_status,
    family_dad_place,
    family_dad_company,
    family_dad_financial_income,
    family_dad_phone,
    family_dad_depend,
    family_dad_no_phone,
    family_dad_time_died,
    family_dad_reason_died,
    family_dad_life,
    family_dad_phone_val,
    family_dad_working_val,
    

    family_mom_name,
    family_mom_age,
    family_mom_status,
    family_mom_place,
    family_mom_company,
    family_mom_financial_income,
    family_mom_phone,
    family_mom_depend,
    family_mom_no_phone,
    family_mom_time_died,
    family_mom_reason_died,
    family_mom_life,
    family_mom_phone_val,
    family_mom_working_val,

    family_stepfather_name,
    family_stepfather_age,
    family_stepfather_status,
    family_stepfather_place,
    family_stepfather_company,
    family_stepfather_financial_income,
    family_stepfather_phone,
    family_stepfather_depend,
    family_stepfather_no_phone,
    family_stepfather_time_died,
    family_stepfather_reason_died,
    family_stepfather_life,
    family_stepfather_phone_val,
    family_stepfather_working_val,
    family_stepfather_info,
    family_stepfather_noInfo,


    family_stepmother_name,
    family_stepmother_age,
    family_stepmother_status,
    family_stepmother_place,
    family_stepmother_company,
    family_stepmother_financial_income,
    family_stepmother_phone,
    family_stepmother_depend,
    family_stepmother_no_phone,
    family_stepmother_time_died,
    family_stepmother_reason_died,
    family_stepmother_info,
    family_stepmother_life,
    family_stepmother_phone_val,
    family_stepmother_working_val,
    family_stepmother_noInfo,
  },
} = generalFormModel;

export default {
  //general
  [general_name.name]: "a",
  [general_lastname.name]: "a",
  [general_place_birth.name]: "a",
  [general_age.name]: "a",
  [general_civil_status.name]: "",
  [general_profession.name]: "a",
  [general_direction.name]: "a",
  [general_time_reside.name]: "a",
  [general_emergency_name.name]: "a",
  [general_emergency_kinship.name]: "a",
  [general_previous_direction.name]: "a",
  [general_phone.name]: "a",
  [general_emergency_phone.name]: "a",
  [general_dpi.name]: "a",
  [general_nit.name]: "a",
  [general_email.name]: "a@gmail.com",
  // you need to keep the default value
  general_birth: new Date().toISOString().split("T")[0],
  vehicle: [],
  license: [],

  //dad
  [family_dad_name.name]: "a",
  [family_dad_age.name]: "a",
  [family_dad_status.name]: "",
  [family_dad_place.name]: "a",
  [family_dad_company.name]: "a",
  [family_dad_financial_income.name]: "a",
  [family_dad_phone.name]: "a",
  [family_dad_depend.name]: "a",
  [family_dad_no_phone.name]: "a",
  [family_dad_time_died.name]: "a",
  [family_dad_reason_died.name]: "a",
  [family_dad_phone.name]: "a",
  [family_dad_life.name] : "",
  [family_dad_phone_val.name]: "",
  [family_dad_working_val.name]: "",

  //mom
  [family_mom_name.name]: "a",
  [family_mom_age.name]: "a",
  [family_mom_status.name]: "",
  [family_mom_place.name]: "a",
  [family_mom_company.name]: "a",
  [family_mom_financial_income.name]: "a",
  [family_mom_phone.name]: "a",
  [family_mom_depend.name]: "a",
  [family_mom_no_phone.name]: "a",
  [family_mom_time_died.name]: "a",
  [family_mom_life.name] : "",
  [family_mom_phone_val.name]: "",
  [family_mom_working_val.name]: "",
  [family_mom_reason_died.name]: "a",

  //stepfather
  [family_stepfather_name.name]: "a",
  [family_stepfather_age.name]: "a",
  [family_stepfather_status.name]: "",
  [family_stepfather_place.name]: "a",
  [family_stepfather_company.name]: "a",
  [family_stepfather_financial_income.name]: "a",
  [family_stepfather_phone.name]: "a",
  [family_stepfather_depend.name]: "a",
  [family_stepfather_no_phone.name]: "a",
  [family_stepfather_time_died.name]: "a",
  [family_stepfather_reason_died.name]: "a" ,
  [family_stepfather_info.name]: "a",
  [family_stepfather_life.name] : "a",
  [family_stepfather_phone_val.name]: "",
  [family_stepfather_working_val.name]: "",
  [family_stepfather_noInfo.name]: "a",

  //stepmother
  [family_stepmother_name.name]: "a",
  [family_stepmother_age.name]: "a",
  [family_stepmother_status.name]: "",
  [family_stepmother_place.name]: "a",
  [family_stepmother_company.name]: "a",
  [family_stepmother_financial_income.name]: "a",
  [family_stepmother_phone.name]: "a",
  [family_stepmother_depend.name]: "a",
  [family_stepmother_no_phone.name]: "a",
  [family_stepmother_time_died.name]: "a",
  [family_stepmother_reason_died.name]: "a",
  [family_stepmother_info.name]: "a",
  [family_stepmother_life.name] : "a",
  [family_stepmother_phone_val.name]: "",
  [family_stepmother_working_val.name]: "a",
  [family_stepmother_noInfo.name]: "a",

  //son
  son: [],
};
