import generalFormModel from "./generalFormModel";
const {
  formField: {
    general_name,
    general_lastname,
    general_age,
    general_place_birth,
    general_civil_status,
    general_profession,
    general_direction,
    general_time_reside,
    general_emergency_name,
    general_emergency_kinship,
    general_previous_direction,
    general_phone,
    general_emergency_phone,
    general_dpi,
    general_nit,
    general_vehicle,
    general_count_vehicle,
    general_license,
    general_license_type,
    general_license_expire,
    general_model,
    general_brand,
    general_email,
  },
} = generalFormModel;

export default {
  [general_name.name]: "example_def",
  [general_lastname.name]: "example_def",
  [general_place_birth.name]: "example_def",
  [general_age.name]: "00",
  [general_civil_status.name]: "example_def",
  [general_profession.name]: "example_def",
  [general_direction.name]: "example_def",
  [general_time_reside.name]: "example_def",
  [general_emergency_name.name]: "example_def",
  [general_emergency_kinship.name]: "example_def",
  [general_previous_direction.name]: "example_def",
  [general_phone.name]: "0000000000",
  [general_emergency_phone.name]: "0000000000",
  [general_dpi.name]: "example_def",
  [general_nit.name]: "example_def",
  [general_email.name]: "mail@gmail.com",
  [general_model.name]: "example_def",
  [general_brand.name]: "example_def",
  // you need to keep the default value
  general_birth: new Date().toISOString().split("T")[0],
  vehicle: [],
  license: [],
};
